---
date: 2018-09-21
title: Barrier Locations
weight: 21
output:
  blogdown::html_page
---

## Interactive Map
Use the map below to explore the locations of current (red) and former (green) barriers in St. Louis. The numbered map symbols  indicate the total number of points being "clustered" together to make the map easier to read when zoomed out. You can click on them to zoom into that area and reveal individual barriers. **If you find an intersection that is missing a barrier, or see a closed intersection that is now open, please let us know [via email](mailto:chris.prener@slu.edu) or by [opening an issue on our GitHub page](https://github.com/chris-prener/barriers-data/issues)!** 
<p> </p>
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(here)
library(leaflet)
library(sf)

load(file = here("static", "allBarriers.rda"))

leaflet(width = '100%', height = '450pt') %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addAwesomeMarkers(
    data = allBarriers, 
    icon = awesomeIcons(
      library = "ion",
      icon = ifelse(
        test = allBarriers$Status == "open",
        yes = "ios-checkmark", 
        no = ifelse(
          test = allBarriers$Status == "closed",
          yes = "ios-close",
          no = "ios-help")  
      ),
      iconColor = "black",  # the icon's colour
      markerColor = ifelse(
        test = allBarriers$Status == "open",  # if this...
        yes = "green",  # ...then colour blue
        no = ifelse(
          test = allBarriers$Status == "closed",  # if this...
          yes = "red",  # ...then colour lightblue
          no = "lightgray"  # colour remaining schools (Ofsted rating RI, I, SW or SM)
        )
      )
    ),
    clusterOptions = markerClusterOptions(),
    popup = paste("Barrier: ", allBarriers$BarrierID, "<br>",
                  "Status: ", allBarriers$Status, "<br>",
                  "Description: ", allBarriers$Descrip, "<br>")
  )
```
<p> </p>

## Download Barrier Data
These location data [are available via GitHub](https://github.com/chris-prener/barriers-data) in four formats: 

* a [`.csv`](https://en.wikipedia.org/wiki/Comma-separated_values) table that can be opened by spreadsheet applications and statistical software, 
* a `.shp` ([ESRI shapefile](https://en.wikipedia.org/wiki/Shapefile)) that can be opened by GIS applications, and 
* [`.geoJSON`](https://en.wikipedia.org/wiki/GeoJSON) and [`.gpkg`](https://en.wikipedia.org/wiki/GeoPackage) files that can also be opened by GIS tools. 

These data are released under an [Open Data Commons Attribution License (ODC-By)](http://opendatacommons.org/licenses/by/1.0/), which is a permissive license that allows the data to be widely reused as long as attribution is provided. The data will be subject to regular updates. We also plan to release additional data about the barriers as we proceed with our project, so please check back often!

## How We Created The Barriers Data
We began buy obtaining a `.pdf` copy of [a paper](https://www.scribd.com/document/31154170/Streets-Not-Through-Analysis-of-the-Blockages-and-Barricades-to-the-St-Louis-Street-Network) written by Stephen Waldron, a former student at Washington University in St. Louis. We made a number of attempts to locate contact information for Waldron and were unable to get the paper directly from him. The paper included a table at the end that listed the location of barriers that Waldron identified. These were digitized by a Saint Louis University student [Jeffrey Meyer](/team) during the spring of 2016, who also checked the barrier locations against Google Street View imagery. This allowed us to locate additional barriers not contained in the original data set, and also identify barriers that were removed since Waldron completed his research.

With a tabular data set containing all of the barriers created, the data were then converted to shapefiles by two additional students, [Kyle Miller](/team) and [Andrew Smith](/team). When Kyle and Andrew created the shapefiles, they also checked the barrier locations against orthoimagery from the [East-West Gateway Council of Governments](http://www.ewgateway.org/research-center/gis-maps/). This work was completed during the fall of 2016.

During the summer of 2017, two new students - [Abby Block](/team) and [Abbey Curran](/team) - began visiting barriers throughout the city. They were assisted towards the end of their fieldwork by a third student, Cree Foeller. When barriers were visited, the latitude and longitude of each closure was noted and the researchers took photos as well as field notes describing the barriers themselves and the surrounding neighborhood. Their data was combined, converted into shapefiles, and compared with our prior list of closures. New barriers were identified during this stage of fieldwork.

A final round of updates, with additional new barriers identified, was completed early in the spring of 2018 by principal investigator [Christopher Prener](/team). These newest barriers identified were located using a combination of Google Street View imagery, satellite data, and block-level shapefiles from the City of St. Louis.
