baseurl = "https://chris-prener.github.io/barriers/"
languageCode = "en-us"
title = "'Street Not Thru': St. Louis Barriers Project"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Christopher Prener, Ph.D."
	description = "Research on Systematic Street Closures in St. Louis, Missouri"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	# Ignore files
	ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = ""
		
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "*Street Not Thru*: \rSt. Louis Barriers Project"
		
		# The icons will be shown if you enter your username
		twitter = ""
		github = "chris-prener"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""
		
		# homepage url
		home="https://chris-prener.github.io/"
		
		copyright = [
			"&copy; 2017-2019 [CC-BY-SA 4.0](/barriers/license)",
			"Design: [HTML5 UP](//html5up.net)",
		]

  [params.avatar]
    hide = true
    
  [params.rss]
    hide = true

	[params.about]
		hide  = false
		title = "Research on Systematic Street Closures in St. Louis, Missouri"
		content = "The City of St. Louis (which is an independent city separate from St. Louis County) has a tremendously fractured street grid, with a variety of physical structures used to create cul-de-sacs or otherwise block traffic from using streets. However, precisely how fractured the city's street grid is remains an open question - [the City does not keep a list of closures](http://www.stltoday.com/news/local/metro/in-a-city-where-street-closings-are-common-schoemehl-pots/article_c191cf1a-4967-5f58-80f4-3d8e3189790f.html). The *Street Not Thru* project began as an effort to document the number of street closures in the city. We have since expanded our efforts to include research studying the demographic patterns that gave rise to the barriers, their effectiveness as crime deterrents, and the consequences of closed streets."


	[params.portfolio]
		hide  = false
		title = "publications and media"

    		# The images and thumbnails are stored under static/images
    		[[params.portfolio.gallery]]
    			image = "barrier1.png"
    			thumb = "barrier1_thumb.png"
    			title = "Preprint: Barriers and Crime"
    			description = "Initial analysis of barrier locations and violent crime, available on <a href='https://osf.io/preprints/socarxiv/2wext/' target = '_blank'>SocArXiv</a> without restriction."
    			
    		[[params.portfolio.gallery]]
    			image = "barrier2.png"
    			thumb = "barrier2_thumb.png"
    			title = "Media"
    			description = "Our work was recently featured in a <a href='https://www.stltoday.com/news/local/crime-and-courts/to-make-st-louis-safer-hundreds-of-streets-were-closed/article_8b3b3042-db3c-59e5-919f-515aa6a0fe7e.html#tracking-source=home-top-story' target = '_blank'>St. Louis Post-Dispatch</a> article on the barriers."


	[params.recentposts]
		hide  = true
		title = "recent articles"

	[params.contact]
		hide  = true
		email = "chris.prener@slu.edu"

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "background"
	url  = "/background"
	weight = 20

[[menu.main]]
	name = "barrier locations"
	url  = "/barriers"
	weight = 21
	
[[menu.main]]
	name = "research team"
	url  = "/team"
	weight = 44
	