---
date: 2018-04-04
title: Barrier Locations
weight: 21
output:
  blogdown::html_page
---

## Interactive Map
Use the map below to explore the locations of current and former barriers in St. Louis. The numbered map symbols  indicate the total number of points being "clustered" together to make the map easier to read when zoomed out. You can click on them to zoom into that area and reveal individual barriers. **If you find an intersection that is missing a barrier, or see a closed intersection that is now open, please [let us know](mailto:chris.prener@slu.edu)!** 

**As we prepare for our initial release of the barriers data, we are providing only a limited preview of barriers in the Shaw neighborhood.**
<p> </p>
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(here)
library(leaflet)
library(sf)

load(file = here("static", "shawBarriers.rda"))

leaflet(width = '100%', height = '450pt') %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addMarkers(data = shawBarriers, 
             clusterOptions = markerClusterOptions(),
             popup = paste("Barrier: ", shawBarriers$BarrierID, "<br>",
                           "Description: ", shawBarriers$Descrip, "<br>"))
```
<p> </p>
## Download Barrier Data
We are preparing the make our data on the inventory of barriers - the same data that are mapped above - available for open access. The data will be released in three formats - a [`.csv`](https://en.wikipedia.org/wiki/Comma-separated_values) table that can be opened by spreadsheet applications and statistical software, an [ESRI shapefile](https://en.wikipedia.org/wiki/Shapefile) that can be opened by GIS applications, and a [`.geoJSON`](https://en.wikipedia.org/wiki/GeoJSON) file that can also be opened by GIS tools. These data will be released under an [Open Data Commons Attribution License (ODC-By)](http://opendatacommons.org/licenses/by/1.0/), which is a permissive license that allows the data to be widely reused as long as attribution is provided. The data will be available through [GitHub](), and will be subject to regular updates. We also plan to release additional data about the barriers as we proceed with our project, so please check back often!